### PR TITLE
Update and adapt enzyme to React 16.2

### LINKED ISSUE #802: Unit tests fail
Unit tests (`npm test`) are currently broken.

The tests fail to run, giving the error:

```
TypeError: (0 , (_jestUtil || _load_jestUtil(...)).validateCLIOptions) is not a function
```

Updating to the latest `jest-cli` (23.5.0) allows the tests to run, but the tests are failing. They seem to be failing since #712.

### PR DESCRIPTION
**Pull request by mirka**
Closes #802 

Tests were failing because Enzyme wasn't cooperating with our current React version (v16.2). Going forward, Enzyme will now [require an adapter package](https://github.com/airbnb/enzyme/blob/HEAD/docs/guides/migration-from-2-to-3.md) specific to the React version.

This fix updates Enzyme and adds an adapter package.

## Test instructions
`npm test` should now run and pass successfully.

### CODE REVIEW

**Comment by roundhill** [comment]
LGTM 👍 

screen shot 2018-08-29 at 4 35 02 pm
