### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#802]
Unit tests (`npm test`) are currently broken.

The tests fail to run, giving the error:

```
TypeError: (0 , (_jestUtil || _load_jestUtil(...)).validateCLIOptions) is not a function
```

Updating to the latest `jest-cli` (23.5.0) allows the tests to run, but the tests are failing. They seem to be failing since #712.
